version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
      - .:/app
    command: ["streamlit", "run", "app.py"]
